### PR TITLE
fix: modify local start-api event headers to lower case

### PR DESCRIPTION
**Pull request by JiJiHoon**
#### Which issue(s) does this change fix?

#3208

#### Why is this change necessary?
It fixes event.headers do not match the specification.
[HTTP APIs, Format 2.0](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-lambda.html)

#### How does it address the issue?
make headers key to lower case.
modify test case expected values.

#### Mandatory Checklist
**PRs will only be reviewed after checklist is complete**

- [ ] Add input/output [type hints](https://docs.python.org/3/library/typing.html) to new functions/methods
- [ ] Write design document if needed ([Do I need to write a design document?](https://github.com/aws/aws-sam-cli/blob/develop/DEVELOPMENT_GUIDE.md#design-document))
- [x] Write/update unit tests
- [x] Write/update integration tests
- [ ] Write/update functional tests if needed
- [x] `make pr` passes
- [ ] `make update-reproducible-reqs` if dependencies were changed
- [ ] Write documentation

By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0).

### CODE REVIEW

**Comment by moelasmar** [comment]
Thanks @JiJiHoon for your participation.

**Review by moelasmar — APPROVED** [review]

**Review by mingkun2020 — APPROVED** [review]
LGTM! Thanks @JiJiHoon for your contribution!

**Comment by jfuss** [comment]
This looks like it lowers all the headers keys, which doesn't match Api Gateway. This has been discussed at good lengths here https://github.com/aws/aws-sam-cli/issues/1860, specifically here: https://github.com/aws/aws-sam-cli/issues/1860#issuecomment-888800663. 

Given past discussions, I don't think we should be taking in this contribution.

**Comment by mndeveci** [comment]
I am closing this PR as per previous discussions. This was also mentioned in the issue linked this one, please check [RFC 2616](https://datatracker.ietf.org/doc/html/rfc2616#page-31) where they specifically mention that http header names are case insensitive;
> HTTP header fields, which include general-header ([section 4.5](https://datatracker.ietf.org/doc/html/rfc2616#section-4.5)),
   request-header ([section 5.3](https://datatracker.ietf.org/doc/html/rfc2616#section-5.3)), response-header ([section 6.2](https://datatracker.ietf.org/doc/html/rfc2616#section-6.2)), and
   entity-header ([section 7.1](https://datatracker.ietf.org/doc/html/rfc2616#section-7.1)) fields, follow the same generic format as
   that given in [Section 3.1 of RFC 822](https://datatracker.ietf.org/doc/html/rfc822#section-3.1) [[9](https://datatracker.ietf.org/doc/html/rfc2616#ref-9)]. Each header field consists
   of a name followed by a colon (":") and the field value. Field names
   are case-insensitive.

**Pull request closed without merging**
