### PR TITLE
Escape double quotes when saving and unwrap only one layer of quotes when reading parameter values ( #2034)

### PR DESCRIPTION
**Pull request by specious**
The function `_unquote_wrapped_quotes()` in `samcli/cli/types.py` was checking if the string is wrapped in quotes, but then performing a greedy removal on both sides.

The documentation wasn't correct either.

All the tests pass after this change.  Perhaps someone could look over this and see if it makes sense.

---

By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0).

### CODE REVIEW

**Comment by specious** [comment]
Escaping double quotes when preparing parameter values for saving in `GuidedConfig.quote_parameter_values()` properly solves  #2034.

**Comment by specious** [comment]
It is now possible to save parameter overrides containing double quote characters, and they will be double-escaped as `\\\"` in `samconfig.toml`. They will be properly read back as double quotes.

**Comment by specious** [comment]
I apologize for not having the time to adjust the test coverage right now. Could anyone kindly give me some pointers as to what needs to be done?

**Comment by awood45** [comment]
It looks like the failure cause is just not having run `black` formatting. I'll try to pull this down and fix that.

**Comment by awood45** [comment]
I can't push to your fork so I've opened #3533 with formatting fixes.

**Comment by specious** [comment]
Fantastic!

**Comment by awood45** [comment]
And merged! Thanks so much!

**Pull request closed without merging**
