### PR TITLE
feat: Custom Lambda authorizer support for local start-api

### PR DESCRIPTION
**Pull request by lucashuy**
#### Why is this change necessary?
Adds support for invoking custom Lambda authorizers that are defined in the template using `sam local start-api`. Both API Gateway V1 and V2 versions will be supported, this includes defining Lambda authorizers in both Cloudformation and SAM resources.

#### How does it address the issue?
Adds the following parsing logic:
- Swagger and OpenApi inline document parsing
- SAM resource property parsing
- Cloudformation resource property parsing

The Lambda authorizer will be invoked before the endpoint Lambda to validate the response.

#### What side effects does this change have?
Previously, templates that contained Lambda authorizers had their authorization logic ignored by `sam local start-api`. Now, any Lambda authorizers that are defined in the template will be setup and will have their logic run.

By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0).

### CODE REVIEW

**Review by moelasmar — APPROVED** [review]

**Comment by ylilarry** [comment]
Does this change forces the authorizer to be locally defined? If the authorizer is defined using a FuncitonArn this will fail?

      Auth: # Uses the UserAppTokenAuthorizer to identify the session user.
        ApiKeyRequired: false
        DefaultAuthorizer: UserAppTokenAuthorizer
        Authorizers:
          UserAppTokenAuthorizer:
            FunctionPayloadType: REQUEST
            FunctionArn: arn:aws:lambda:us-east-1:xxxxxxxxxxxx:function:UserAppTokenAuthorizer

**Comment by lucashuy** [comment]
The `FunctionArn` should reference a locally defined Lambda authorizer. Referencing and invoking a Lambda authorizer that is deployed to AWS within `sam local start-api` is not supported.

**Comment by ylilarry** [comment]
Ok. That explains #5037. But this is now a breaking change. Wouldn't it be better in my case `sam local start-api` outputs a warning saying `Using an authorizer defined by FunctionArn is not supported` and keep the 1.79 behaviour in this case? Because in my project the Authorizer is defined in a different repo and I don't see a way to work around #5037 now.

**Comment by ken-guo1** [comment]
This release indeed is a killer but I am still unable to use the local authorizer after trying out different things. From the debug log I can see that the authorizer is been set to `None`. I suspect that my `AWS::Serverless::HttpApi` is not created properly or not even created. I tried to follow the template as close to this test commit [https://github.com/aws/aws-sam-cli/pull/5005/files#diff-f5af499800120973b221fbd1c2eba394c4d5f17d787e8f32790a8ce35302752e](url) 

SAM cli version:  1.80.0

debug console:
```
sam    | 2023-04-20 17:22:15,990 | local start-api command is called
sam    | 2023-04-20 17:22:15,995 | Collected default values for parameters: {'AuthOverride': 'LambdaAuthorizer', 'AuthHandler': 'app.auth_handler', 'AuthSimpleHandler': 'app.simple_handler'}
sam    | 2023-04-20 17:22:16,011 | There is no customer defined id or cdk path defined for resource ServerlessHttpApi, so we will use the resource logical id as the resource id
sam    | 2023-04-20 17:22:16,011 | There is no customer defined id or cdk path defined for resource getSessionFunction, so we will use the resource logical id as the resource id
sam    | 2023-04-20 17:22:16,011 | There is no customer defined id or cdk path defined for resource AuthorizerFunction, so we will use the resource logical id as the resource id
sam    | 2023-04-20 17:22:16,011 | There is no customer defined id or cdk path defined for resource AuthorizerPermission, so we will use the resource logical id as the resource id
sam    | 2023-04-20 17:22:16,011 | There is no customer defined id or cdk path defined for resource RuntimeDependenciesLayer, so we will use the resource logical id as the resource id
sam    | 2023-04-20 17:22:16,012 | 0 stacks found in the template
sam    | 2023-04-20 17:22:16,012 | Collected default values for parameters: {'AuthOverride': 'LambdaAuthorizer', 'AuthHandler': 'app.auth_handler', 'AuthSimpleHandler': 'app.simple_handler'}
sam    | 2023-04-20 17:22:16,021 | There is no customer defined id or cdk path defined for resource ServerlessHttpApi, so we will use the resource logical id as the resource id
sam    | 2023-04-20 17:22:16,021 | There is no customer defined id or cdk path defined for resource getSessionFunction, so we will use the resource logical id as the resource id
sam    | 2023-04-20 17:22:16,021 | There is no customer defined id or cdk path defined for resource AuthorizerFunction, so we will use the resource logical id as the resource id
sam    | 2023-04-20 17:22:16,021 | There is no customer defined id or cdk path defined for resource AuthorizerPermission, so we will use the resource logical id as the resource id
sam    | 2023-04-20 17:22:16,021 | There is no customer defined id or cdk path defined for resource RuntimeDependenciesLayer, so we will use the resource logical id as the resource id
sam    | 2023-04-20 17:22:16,021 | 5 resources found in the stack 
sam    | 2023-04-20 17:22:16,021 | --base-dir is not presented, adjusting uri ./ relative to /Users/kenguo/Documents/workspace/connecx/monorepo/lambda/template.yml
sam    | 2023-04-20 17:22:16,021 | Found Serverless function with name='getSessionFunction' and CodeUri='.'
sam    | 2023-04-20 17:22:16,021 | --base-dir is not presented, adjusting uri . relative to /Users/kenguo/Documents/workspace/connecx/monorepo/lambda/template.yml
sam    | 2023-04-20 17:22:16,021 | --base-dir is not presented, adjusting uri ./ relative to /Users/kenguo/Documents/workspace/connecx/monorepo/lambda/template.yml
sam    | 2023-04-20 17:22:16,021 | Found Serverless function with name='AuthorizerFunction' and CodeUri='.'
sam    | 2023-04-20 17:22:16,021 | --base-dir is not presented, adjusting uri . relative to /Users/kenguo/Documents/workspace/connecx/monorepo/lambda/template.yml
sam    | 2023-04-20 17:22:16,025 | Detected Inline Swagger definition
sam    | 2023-04-20 17:22:16,026 | Parsing Swagger document using 3.0 specification
sam    | 2023-04-20 17:22:16,026 | Lambda function integration not found in Swagger document at path='/sessions' method='get'
sam    | 2023-04-20 17:22:16,026 | Found '0' APIs in resource 'ServerlessHttpApi'
sam    | 2023-04-20 17:22:16,026 | Found '0' authorizers in resource 'ServerlessHttpApi'
sam    | 2023-04-20 17:22:16,026 | Found '1' API Events in Serverless function with name 'getSessionFunction'
sam    | 2023-04-20 17:22:16,026 | Found '0' API Events in Serverless function with name 'AuthorizerFunction'
sam    | 2023-04-20 17:22:16,026 | Removed duplicates from '0' Explicit APIs and '1' Implicit APIs to produce '1' APIs
sam    | 2023-04-20 17:22:16,026 | Linking authorizer skipped for route '/sessions', authorizer 'None' is unsupported or not found
sam    | 2023-04-20 17:22:16,026 | 1 APIs found in the template
sam    | 2023-04-20 17:22:16,029 | Mounting getSessionFunction at http://127.0.0.1:3000/sessions [GET]
sam    | 2023-04-20 17:22:16,029 | You can now browse to the above endpoints to invoke your functions. You do not need to restart/reload SAM CLI while working on your functions, changes will be reflected instantly/automatically. If you used sam build before running local commands, you will need to re-run sam build for the changes to be picked up. You only need to restart SAM CLI if you update your AWS SAM template
sam    | 2023-04-20 17:22:16,029 | Localhost server is starting up. Multi-threading = True
sam    | 2023-04-20 17:22:16 WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
sam    |  * Running on http://127.0.0.1:3000
```


my template.yaml

```
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  aws-sam-typescript-local-development
# Transform section specifies one or more macros that AWS CloudFormation uses to process your template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/transform-section-structure.html
Transform:
  - AWS::Serverless-2016-10-31

Globals:
  Function:
    Layers:
      - !Ref RuntimeDependenciesLayer
    Runtime: nodejs18.x
    MemorySize: 512
    Timeout: 3000

Parameters:
  AuthOverride:
    Default: LambdaAuthorizer
    Type: String
  AuthHandler:
    Default: app.auth_handler
    Type: String
  AuthSimpleHandler:
    Default: app.simple_handler
    Type: String

# Resources declares the AWS resources that you want to include in the stack
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
Resources:
  ServerlessHttpApi:
    Type: AWS::Serverless::HttpApi
    Name: 'ServerlessHttpApi'
    Properties:
      StageName: http
      # Lambda auth suppport, but it is somehow still ignored. SAM CLI version: 1.80.0
      # https://github.com/aws/aws-sam-cli/pull/5005
      Auth:
        DefaultAuthorizer: LambdaAuthorizer
        FailOnWarnings: true
        Authorizers:
          LambdaAuthorizer:
            #FunctionArn: !GetAtt AuthorizerFunction.Arn
            FunctionInvokeRole: !GetAtt AuthorizerFunction.Arn
            Identity:
              Headers:
                - header
            AuthorizerPayloadFormatVersion: '2.0'
            EnableSimpleResponses: true

  getSessionFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Handler: dist/functions/get-session/handler.handler
      Description: get session handler
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            Auth:
              Authorizer: !Ref AuthOverride

            Path: /sessions
            Method: GET
            ApiId: !Ref ServerlessHttpApi
            RestApiId: !Ref ServerlessHttpApi

  AuthorizerFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Handler: dist/functions/authorizer/handler.handler
      Description: lambda authorizer handler

  AuthorizerPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref AuthorizerFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com

  RuntimeDependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Metadata:
      BuildMethod: makefile
    Properties:
      Description: Runtime dependencies for Lambdas
      ContentUri: ./
      CompatibleRuntimes:
        - nodejs18.x
      RetentionPolicy: Retain


```

**Comment by howardkitto** [comment]
Understand that this only work with custom authorisers, so it would be great to have a local cognito simulator lambda template that delivers event data in the same format and an environment switch so that this can run locally and cognito user pools are used when this is running in the cloud.

**Comment by lucasgismondi-gg** [comment]
This is amazing, thank you for implementing this. One issue is that it doesn't seem to respect lambdas that override the default API Gateway authorizer. When I set the authorizer to "NONE" it will still use the default authorizer. Anyone else run into this?

**Pull request merged**
