### PR TITLE
fix: Use abs path to upload stackset template on S3

### PR DESCRIPTION
**Pull request by maintux**
#### Which issue(s) does this change fix?
None

#### Why is this change necessary?
This is useful to run `sam package` after a `sam build` command. The stack set template will point to a relative path external to the `.aws-sam`. So in order to upload it on S3 we need to use the abs path instead of the relative one.

#### How does it address the issue?
Use pre-calculated abs_template_path

#### What side effects does this change have?
None

#### Mandatory Checklist
**PRs will only be reviewed after checklist is complete**

- [ ] Add input/output [type hints](https://docs.python.org/3/library/typing.html) to new functions/methods
- [ ] Write design document if needed ([Do I need to write a design document?](https://github.com/aws/aws-sam-cli/blob/develop/DEVELOPMENT_GUIDE.md#design-document))
- [ ] Write/update unit tests
- [ ] Write/update integration tests
- [ ] Write/update functional tests if needed
- [x] `make pr` passes
- [ ] `make update-reproducible-reqs` if dependencies were changed
- [ ] Write documentation

By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0).

### CODE REVIEW

**Comment by moelasmar** [comment]
Thanks @maintux for your participation. 
Can I ask you to add an integration test case to clarify your use case?

**Comment by maintux** [comment]
Hi @moelasmar, 
Integration test added. Regarding the unit test, the current tests already cover this case.

Thanks

**Review by moelasmar — APPROVED** [review]

**Comment by moelasmar** [comment]
Thanks @maintux for your contribution

**Review by mingkun2020 — APPROVED** [review]
LGTM! Thanks @maintux for your contribution

**Comment by jplock** [comment]
Related to https://github.com/aws/aws-sam-cli/pull/3674 and https://github.com/aws/aws-sam-cli/issues/2249

**Review by jfuss — APPROVED** [review]

**Comment by maintux** [comment]
Hi guys, when do you think this will be merged and released?

**Pull request merged**
