### PR TITLE
fix: Writing to bytes TextIO stream in StreamWriter causing AttributeError on buffer member

### PR DESCRIPTION
**Pull request by sbchisholm**
#### Which issue(s) does this change fix?
#6033

#### Why is this change necessary?
Fixes the bug raise in #6033 where the instance of the stream member in StreamWriter does not have the buffer attribute.

#### How does it address the issue?
Rather than using the buffer attribute to write bytes, the bytes are converted to a string first with decode and then written with the write method (which accepts strings)

#### What side effects does this change have?
Unsure.

#### Mandatory Checklist
**PRs will only be reviewed after checklist is complete**

- [ ] Add input/output [type hints](https://docs.python.org/3/library/typing.html) to new functions/methods
- [ ] Write design document if needed ([Do I need to write a design document?](https://github.com/aws/aws-sam-cli/blob/develop/DEVELOPMENT_GUIDE.md#design-document))
- [ ] Write/update unit tests
- [ ] Write/update integration tests
- [ ] Write/update functional tests if needed
- [ ] `make pr` passes
- [ ] `make update-reproducible-reqs` if dependencies were changed
- [ ] Write documentation

By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0).

### CODE REVIEW

**Comment by wolverian** [comment]
Looking at the users of this function, for example https://github.com/aws/aws-sam-cli/blob/8126aaac29ff8706b14f29a126ab7bb829d81b24/samcli/local/docker/container.py#L476-L478 and https://github.com/aws/aws-sam-cli/blob/8126aaac29ff8706b14f29a126ab7bb829d81b24/samcli/commands/remote/remote_invoke_context.py#L276 would it make more sense to remove this function and change the calls to use `write_str` instead?

**Comment by sbchisholm** [comment]
> Looking at the users of this function, for example
> 
> https://github.com/aws/aws-sam-cli/blob/8126aaac29ff8706b14f29a126ab7bb829d81b24/samcli/local/docker/container.py#L476-L478
> 
> and
> https://github.com/aws/aws-sam-cli/blob/8126aaac29ff8706b14f29a126ab7bb829d81b24/samcli/commands/remote/remote_invoke_context.py#L276
> 
> would it make sense to remove this function and change the calls to use `write_str` instead?

If that's true, then that would make sense but it looks to also be used in here:
https://github.com/aws/aws-sam-cli/blob/8126aaac29ff8706b14f29a126ab7bb829d81b24/samcli/local/docker/container.py#L367-L368

**Comment by wolverian** [comment]
Sure, but does that make sense? In that case, if this PR is merged, the bytes are decoded to a string anyway, it's just hidden from the caller and could surprise them if they assumed the bytes wouldn't be interpreted in any specific encoding. 

Rather, either this abstraction should offer a real way to write raw bytes with no interpretation (decoding) _or_ it should only offer a way to write strings. Hiding these string to bytes and back conversions will shoot the user in the foot eventually.

**Comment by sbchisholm** [comment]
> Sure, but does that make sense? In that case, if this PR is merged, the bytes are decoded to a string anyway, it's just hidden from the caller and could surprise them if they assumed the bytes wouldn't be interpreted in any specific encoding.
> 
> Rather, in my opinion, either this abstraction should offer a way to write raw bytes with no interpretation (decoding) _or_ it should _only_ offer a way to write strings.
> 
> Hiding these bytes to string conversions will shoot the user in the foot eventually.

That's a great point, I'll update the PR.

**Comment by sriram-mv** [comment]
I'm adding both @jfuss and @mildaniel as reviewers given their previous experience in bytes/str operation.

My take is that we are explicitly changing behavior from bytes to str and there could be side-effects. There was an explicit PR to decode - replace carriage returns - reencode. That behavior seems to be removed at this point.

**Comment by wolverian** [comment]
> My take is that we are explicitly changing behavior from bytes to str and there could be side-effects. There was an explicit PR to decode - replace carriage returns - reencode. That behavior seems to be removed at this point.

It might be a good idea to triage which commit triggered this bug. That might help with figuring out what the right thing to do here is. FWIW,  I think this PR looks logical, but I'm unfamiliar with this codebase and its history.

This is fairly high in priority in my opinion as I simply can't use the latest version SAM CLI right now due to this bug.

**Comment by mildaniel** [comment]
I did some digging here and it seems as though the issue is that the `StreamWriter` class expects the stream to be of type `TextIO`, but there are times where an `io.StringIO` is passed in https://github.com/aws/aws-sam-cli/blob/develop/samcli/local/lambda_service/local_lambda_invoke_service.py#L165. 

`io.StringIO` is not of type `TextIO` and does not have a buffer property that `StreamWriter` expects of a `TextIO` object. I'm not sure why this wasn't picked up by any type checking, but in any case, causes this exception whenever it's called with an `io.StringIO` stream. Changing the instantiators of the `StreamWriter` class to all use `TextIO` would require pretty significant refactoring since those instances also use methods and properties unique to `io.StringIO`. 

Although this PR is more of a solution to the symptom rather than root cause, I'm inclined to go with it so I don't really see any negatives here and it allows us to patch an important issue. Another solution is to update the type in the `StreamWriter` class to be a union of `StreamWriter`, `io.TextIO` and `io.TextIOWrapper` and handle each one in the implementation of the `write` method.

@sriram-mv what are your thoughts here?

**Review by mildaniel — APPROVED** [review]

**Review by moelasmar — APPROVED** [review]

**Pull request merged**
