### PR TITLE
fix: Fix S3 bucket policy issue for sam pipeline

### PR DESCRIPTION
**Pull request by xazhao**
#### Which issue(s) does this change fix?
`sam pipeline bootstrap` is broken because of a S3 [security change](https://aws.amazon.com/blogs/aws/heads-up-amazon-s3-security-changes-are-coming-in-april-of-2023/)

The default value of `ObjectOwnership` becomes `BucketOwnerEnforced` which has conflicts with `AccessControl` property. Hence the deployment will fail.

#### How does it address the issue?

Specify `ObjectOwnership` to `ObjectWriter` so that it doesn't have conflicts with `AccessControl`

#### Mandatory Checklist
**PRs will only be reviewed after checklist is complete**

- [ ] Add input/output [type hints](https://docs.python.org/3/library/typing.html) to new functions/methods
- [ ] Write design document if needed ([Do I need to write a design document?](https://github.com/aws/aws-sam-cli/blob/develop/DEVELOPMENT_GUIDE.md#design-document))
- [ ] Write/update unit tests
- [ ] Write/update integration tests
- [ ] Write/update functional tests if needed
- [ ] `make pr` passes
- [ ] `make update-reproducible-reqs` if dependencies were changed
- [ ] Write documentation

By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0).

### CODE REVIEW

**Review by aahung — APPROVED** [review]
nit: leave a comment there?

**Review by moelasmar — APPROVED** [review]

**Review by sriram-mv — APPROVED** [review]

**Comment by hawflau** [comment]
#5077

**Comment by cmoutafidis** [comment]
Does the fact that this fix is merged mean that the issue should have been resolved?
Because sam pipeline init fails with the same error response. I am guessing the fix is not deployed yet.

**Comment by matt-whyard** [comment]
I am completely stuck without this fix, any idea when it will be released?

**Pull request merged**
