### PR TITLE
fix: Fix `--docker-volume-basedir` being ignored for sam local

### PR DESCRIPTION
**Pull request by lucashuy**
#### Which issue(s) does this change fix?
#2837

#### Why is this change necessary?
This changes fixes `--docker-volume-basedir` not being used to resolve a relative code URI in the template file. Previously, the code URI was automatically resolved to an absolute path, causing checks later on to ignore the directory passed by `--docker-volume-basedir` since the code URI had already been resolved.

#### How does it address the issue?
If the command flag is passed, the invoke context will set `use_raw_codeuri=True` to the function providers, making sure that the code URI stays relative until the end.

#### Mandatory Checklist
**PRs will only be reviewed after checklist is complete**

- [x] Add input/output [type hints](https://docs.python.org/3/library/typing.html) to new functions/methods
- [ ] Write design document if needed ([Do I need to write a design document?](https://github.com/aws/aws-sam-cli/blob/develop/DEVELOPMENT_GUIDE.md#design-document))
- [x] Write/update unit tests
- [ ] Write/update integration tests
- [ ] Write/update functional tests if needed
- [x] `make pr` passes
- [ ] `make update-reproducible-reqs` if dependencies were changed
- [ ] Write documentation

By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0).

### CODE REVIEW

**Review by mildaniel — APPROVED** [review]

**Review by hnnasit — APPROVED** [review]

**Comment by ffMathy** [comment]
@hnnasit this has not been resolved. It is still an issue.

**Comment by grouu-tech** [comment]
+1 totally not fixed yet.

**Comment by ffMathy** [comment]
Cc @lucashuy

**Comment by LinmeiJ** [comment]
Not fixed!

**Comment by yorigcs** [comment]
Not working yet!

**Comment by Logan-Dang** [comment]
Not working yet

**Pull request merged**
