### PR TITLE
Add CORS Headers to Lambda API

### PR DESCRIPTION
**Pull request by awood45**
Ported from https://github.com/lambci/docker-lambda/commit/20fca7e5121e4b8e40fe68d6a826220d0389d012

Don't merge yet, want to see tests run as we review.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by mhart** [comment]
Will also need https://github.com/lambci/docker-lambda/commit/46ff80e2fe3bbb3fab4fa18ac2fb05d7167f064e

**Comment by shadow-light** [comment]
Just ran into this issue. Any reason why haven't merged yet?

**Comment by moelasmar** [comment]
I think as we moved to use aws-lambda-rie rapid server, this PR is not valid any more.
@awood45 Shall we close this PR.

**Comment by mhart** [comment]
@moelasmar so long as the aws-lambda-rie exposes the correct CORS headers, this issue can be closed. Seems that @shadow-light ran into an issue with it though – not sure which version of SAM CLI?

**Comment by jfuss** [comment]
Closing as SAM CLI now uses AWS Lambda Runtime Interface Emulator instead.

**Comment by mhart** [comment]
@jfuss is there a corresponding issue at that repo, or is this not an issue with the rie?

**Pull request closed without merging**
