### PR TITLE
Layer Deployment Permission Issue

### PR DESCRIPTION
**Pull request by CoshUS**
*Issue #, if available:*
https://github.com/aws/aws-sam-cli/issues/2344
*Why is this change necessary?*
Lambda needs read permission as owner on artifacts.

*How does it address the issue?*
Changed Windows mocked permission to 755, mimicking Unix system.
Previously, it was changed from default 644 to 005 to give execute permission for go artifacts. Owner and group owner permission bits were removed assuming Lambda itself (not the user executing the code) do not need permission on the artifacts. However, as regression issue https://github.com/aws/aws-sam-cli/issues/2344 stated, it does require read permission on the Layer artifacts.

There should be no security concern as owner and group owner are set and used by Lambda.

*What side effects does this change have?*
Owner and group owner permission bits will be set to 7 and 5 respectively.

*Did you change a dependency in `requirements/base.txt`?*
    *If so, did you run `make update-reproducible-reqs`*

*Checklist:*

- [ ] Write Design Document ([Do I need to write a design document?](https://github.com/awslabs/aws-sam-cli/blob/develop/DEVELOPMENT_GUIDE.rst#design-document))
- [ ] Write unit tests
- [ ] Write/update functional tests
- [ ] Write/update integration tests
- [ ] `make pr` passes
- [ ] Write documentation

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by mndeveci — APPROVED** [review]
LGTM, and I tested it on Windows and confirmed it is working.

**Review by qingchm — APPROVED** [review]

**Comment by awsjeffg** [comment]
@CoshUS THANK YOU!

**Comment by OK-Apps** [comment]
still getting same problem even with version 1.9.0 :

$ sam --version
SAM CLI, version 1.9.0

-----

PDATE_FAILED            AWS::Lambda::Function    StagingKinesisSenderEx   Layer conversion
                                                  tended                   failed: Some files do
                                                                           not have read
                                                                           permissions; (Service:
                                                                           AWSLambdaInternal;
                                                                           Status Code: 400;
                                                                           Error Code: InvalidPar
                                                                           ameterValueException;
                                                                           Request ID: 4db54727-3
                                                                           8f7-41c9-a648-655361a2
                                                                           2882; Proxy: null)
UPDATE_FAILED            AWS::Lambda::Function    StagingKinesisPutRecor   Layer conversion
                                                  d                        failed: Some files do
                                                                           not have read
                                                                           permissions; (Service:
                                                                           AWSLambdaInternal;
                                                                           Status Code: 400;
                                                                           Error Code: InvalidPar
                                                                           ameterValueException;
                                                                           Request ID: a05a655b-0
                                                                           cfb-4f57-9025-2ab308b2
                                                                           068d; Proxy: null)
UPDATE_ROLLBACK_IN_PRO   AWS::CloudFormation::S   Staging-StagingKinesis   The following
GRESS                    tack                                              resource(s) failed to
                                                                           update: [StagingKinesi
                                                                           sSenderExtended, Stagi
                                                                           ngKinesisPutRecor


---

**Comment by CoshUS** [comment]
@OK-Apps It seems this could be caused by wrong permission set in the existing resource with previous version of SAM CLI. Can you try manually deleting those two resources and re-deploy again?

**Comment by OK-Apps** [comment]
> @OK-Apps It seems this could be caused by the wrong permission set in the existing resources using the previous version of SAM CLI. Can you try manually deleting those two resources and re-deploy again?

@CoshUS by "resource" do you mean the lambda functions or the lambda layers ? (or both?)
and, 
in case if it is only about lambda functions (and not layers) - 
if I was able to successfully do a 'sam deploy; from a non-Windows machine (mac) - so does it count as same effect 
as "manually delete"? - so would we expect if we now try again from a windows machine with 1.9.0 

thank you!

**Comment by CoshUS** [comment]
@OK-Apps 

> do you mean the lambda functions or the lambda layers ? (or both?)

My hunch would be only layers, but try delete or overriding both.

> if I was able to successfully do a 'sam deploy; from a non-Windows machine (mac) - so does it count as same effect
as "manually delete"? - so would we expect if we now try again from a windows machine with 1.9.0

If your deployment on Mac overrides the existing layer artifact with correct permission bits, then it should be the same as deleting and creating a new one.

Thanks!

**Comment by OK-Apps** [comment]
@CoshUS 

an update of current state of affairs - everyone in a team has SAM CLI 1.9.0
when doing 'sam build' & 'sam deploy' from Mac - all works ok
when doing same from various Windows 10 machines - getting the error:

Layer conversion failed: Some files do not have read permissions; 
(Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException;
Request ID: 4df2bf50-f584-4e85-9538-5173260b072e; Proxy: null)

**Comment by OK-Apps** [comment]
@CoshUS so puled how is it even possible - if things take place at server-side- at AWS, 
why it behaves differently when triggering it from Mac VS Windows ?

**Comment by OK-Apps** [comment]
@CoshUS 
regarding layers themselves - some layers we did not even use sam to create them - they been created/uploaded "manually" into AWS console

so what we need to do with those layers? (if we need to do anything with layers to fix this)

**Comment by CoshUS** [comment]
@OK-Apps 
A few clarifying questions:

**Comment by CoshUS** [comment]
A few clarifying questions:
> regarding layers themselves - some layers we did not even use sam to create them - they been created/uploaded "manually" into AWS console

Were the layers created with sam deployed using SAM CLI 1.7.0 or 1.8.0 on Windows?

> an update of current state of affairs - everyone in a team has SAM CLI 1.9.0
when doing 'sam build' & 'sam deploy' from Mac - all works ok
when doing same from various Windows 10 machines - getting the error:

Are these deployments using the same layers and the same Lambdas? 

------

> how is it even possible - if things take place at server-side- at AWS

Lambda is based on Linux which uses unix permission bits. When packaging a layer artifact, Windows does not set permission bits in the zip file which can cause missing permission errors when uploaded and unpacked into Lambda. We changed this behavior in 1.7.0 and forced all file permissions to be 005 when packaged in Windows. This had unintended consequences in deploying layers that can result in `Layer conversion failed: Some files do not have read permissions;` We then changed the permission to 755 to be more permissible in SAM CLI 1.9.0. 

If your layers are created manually in Windows, it should have the default 644 permission and not cause read permission issue.

**Comment by kurax** [comment]
I'm using the lastest release of SAM CLI as 1.10.0 and this issue still remains.
I've deleted all my deployed functions by comment them out in template.yml, then uncomment try to recreate and got this:
> Layer conversion failed: Some files do not have read permissions; (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: 194fed35-a3b8-4ed5-8b17-d93823171bbc; Proxy: null)

Any ideas?

**Comment by OK-Apps** [comment]
HI @CoshUS 
thank you for update - and yes it is our understadning s well ... we have observed the issue with Windows permisions in GoLang  lambda
and seen them fixed in 1.7 ... but then started seeing this "layers issue" with Python lambdas
and now even with 1.9 - still experiencing it (on Windows machines !!)
despite the fact that 
"layers are created manually in Windows, it should have the default 644 permission and not cause read permission issue."

yes all our Python layers been manually created on Windows and yet we still get this error with SAM CLI 1.9 when running 
on Windows machines

**Comment by CoshUS** [comment]
@OK-Apps  @kurax 
Thanks for the information. Created issue #2392 to track this problem.

`Is any version of SAM CLI expected to fix/solve this?`
SAM CLI 1.6.2 does not have the Go permission fix. Can you give that a try?

**Comment by CoshUS** [comment]
@OK-Apps 
Are you able to provide a sample template that reproduces the issue?

**Comment by OK-Apps** [comment]
@CoshUS 

> @OK-Apps
> Are you able to provide a sample template that reproduces the issue?

pls see attached template.zip


also, 
yes it worked ok under SAM CLI 1.5/1.6 

thank you!
[template.yml.zip](https://github.com/aws/aws-sam-cli/files/5610079/template.yml.zip)

**Comment by esscott2112** [comment]
I am having the exact same issue with Window machine.  SAM deployment works with Linux but not Windows for all the reasons listed.  When will this be fixed in the SAM so my development team can SAM deploy from windows machine?

**Pull request merged**
