### PR TITLE
SAM CLI Refresh 🎉: `sam init`, Better validation, Tons of bug fixes, and 🐍

### PR DESCRIPTION
**Pull request by sanathkr**
*Issue #, if available:*

*Description of changes:*
This release is an important milestone - New command to get started with SAM apps, full fidelity SAM Template validation, tons of bug fixes, and greatly improved stability. Oh did I mention, we rewrote the entire CLI from ground up?! Yes, in 🐍. With this refresh, SAM CLI uses the recently open sourced transform, enabling you leverage any new SAM functionality immediately after release.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by claudiobizzotto** [comment]
@sanathkr `samples` folder seems to have been deleted.

**Comment by jfuss** [comment]
@claudiobizzotto Samples/examples can be found over in the [Serverless Application Model repo](https://github.com/awslabs/serverless-application-model/tree/develop/examples). There are many more over there and are being actively maintained.

I will update the README to reflect this.

**Comment by kienpham2000** [comment]
Hey guys, just wanted to learn why a switch from Go to Python for this repo? I love Python as well, just wanted to learn the reasoning behind it, is it because SAM was written in Python? Thank you.

**Comment by sanathkr** [comment]
@kienpham2000  Precisely. We switched because we wanted to provide full fidelity support for all SAM features in the CLI. This is possible only by bundling the official SAM implementation (written in Python) with the CLI. Hence the switch. The rewrite also changed the architecture of the CLI extensively. It will set us up for a faster pace of innovation :)

**Comment by kienpham2000** [comment]
@sanathkr Thanks for the explanation and awesome work. We love sam!

**Pull request merged**
