### PR TITLE
Require Flask 1.1.4

### PR DESCRIPTION
**Pull request by dmarinuswoodwing**
#### Which issue(s) does this change fix?
#3791 
#3792 

#### Why is this change necessary?

Some python package managers (poetry) aren't able to upgrade flask to the latest supported version:

See: https://github.com/python-poetry/poetry/issues/5728

older versions of flask are broken.

#### How does it address the issue?

update the minimal version for flask to a working one

#### What side effects does this change have?

users are required to update flask

#### Mandatory Checklist
**PRs will only be reviewed after checklist is complete**

- ~Add input/output [type hints](https://docs.python.org/3/library/typing.html) to new functions/methods~
- ~Write design document if needed ([Do I need to write a design document?](https://github.com/aws/aws-sam-cli/blob/develop/DEVELOPMENT_GUIDE.md#design-document))~
- ~Write/update unit tests~
- ~Write/update integration tests~
- ~Write/update functional tests if needed~
- [x] `make pr` passes
- [x] `make update-reproducible-reqs` if dependencies were changed
- ~Write documentation~

By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0).

### CODE REVIEW

**Comment by moelasmar** [comment]
Thanks @dmarinuswoodwing  for raising this PR. I just need to know did you face this issue when you try to use the suggested ways to install SAM CLI [here](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-install.html)

**Comment by dmarinuswoodwing** [comment]
Hi @moelasmar ! No, I think this only happens when you install SAM CLI from https://pypi.org/project/aws-sam-cli/ (See `pip install aws-sam-cli` at the top) together with other Python packages (in our case moto).

**Comment by Duchynko** [comment]
@moelasmar what is the status of this PR? I see you added `blocked/close-if-inactive` label—is there something missing before it can be merged?

**Comment by Duchynko** [comment]
@moelasmar what is the status of this PR? I see you added `blocked/close-if-inactive` label—is there something missing before it can be merged?

**Comment by dmarinuswoodwing** [comment]
@moelasmar I'm pretty sure the installer would also break when jinja2, werkzeug or itsdangerous get updated which is allowed by flask 1.1.2.

**Review by hawflau — APPROVED** [review]

**Review by mndeveci — APPROVED** [review]

**Pull request merged**
