### PR TITLE
 feat: Allow to specify the name of the Docker image with which the container is build

### PR DESCRIPTION
**Pull request by khamaileon**
*Issue #, if available:*

#1231 #1605 #1499 and maybe others.

*Description of changes:*

Allow to specify the name of the Docker image with which the container is build

*Checklist:*

- [ ] Write Design Document ([Do I need to write a design document?](https://github.com/awslabs/aws-sam-cli/blob/develop/DEVELOPMENT_GUIDE.rst#design-document))
- [ ] Write unit tests
- [ ] Write/update functional tests
- [ ] Write/update integration tests
- [ ] `make pr` passes
- [ ] Write documentation

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by sanathkr** [comment]
Thanks for the PR. This is a good feature request and a PR. I am wondering if it's easier to allow customers to specify path to a Dockerfile that SAM CLI will build/maintain as a base image. It will allow for a simpler user experience and potentially be more powerful. 

Since this is adding a new CLI argument, a one-way door, I want to explore the Dockerfile option in more detail before taking this on. 

What are your thoughts?

**Comment by khamaileon** [comment]
@sanathkr Yes I agree with you, the use of a Dockerfile would be the ideal solution. [serverless-python-requirements](https://github.com/UnitedIncome/serverless-python-requirements) (an extension for the Serverless framework) made a pretty good job about that.

For me, the custom Docker image and the ability to dynamically include or exclude files during build are the 2 big missing features in the deployment of Python projects.

**Comment by prcongithub** [comment]
Is there any solution to this? I hava a lambda function which depends on a private git repo.
Any workaround for this?

**Comment by polothy** [comment]
Using `Dockerfile` would make it easier to use alternative image locations (Like ECR or a Docker Proxy) in order to get around the new DockerHub Rate Limiting.

https://aws.amazon.com/blogs/containers/advice-for-customers-dealing-with-docker-hub-rate-limits-and-a-coming-soon-announcement/

**Comment by khamaileon** [comment]
Now that we can use a Docker image as a lambda deployment package, I consider this problem solved! Thanks to the AWS SAM team!

**Pull request closed without merging**
