### PR TITLE
feat: Add flag for using npm ci in node builds

### PR DESCRIPTION
**Pull request by mildaniel**
#### Which issue(s) does this change fix?

Add flag in the template file to enable using `npm ci` in lambda builders instead of `npm install`.

Configuration is done through the metadata `BuildProperties` (same as configuring esbuild)
```
AppFunction:
    Type: AWS::Serverless::Function
    Properties:
        CodeUri: hello-world/
        Handler: app.lambdaHandler
        Runtime: nodejs14.x
        Architectures:
          - x86_64
    Metadata:
        BuildProperties: 
            UseNpmCi: True
```

#### Checklist

- [ ] Add input/output [type hints](https://docs.python.org/3/library/typing.html) to new functions/methods
- [ ] Write design document ([Do I need to write a design document?](https://github.com/aws/aws-sam-cli/blob/develop/DEVELOPMENT_GUIDE.md#design-document))
- [x] Write unit tests
- [ ] Write/update functional tests
- [ ] Write/update integration tests
- [x] `make pr` passes
- [ ] `make update-reproducible-reqs` if dependencies were changed
- [ ] Write documentation

By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0).

### CODE REVIEW

**Review by torresxb1 — APPROVED** [review]

**Review by hawflau — APPROVED** [review]
LGTM!

**Comment by leftfieldhero** [comment]
Can someone say why this was reverted? Was there an error? Did it cause a problem? Is there another way for npm ci to be called during a sam build rather than npm i? Otherwise package-lock.json is kinda meaningless when looking for a production build.

**Comment by torresxb1** [comment]
Hi @leftfieldhero , the revert was reverted in https://github.com/aws/aws-sam-cli/pull/3741. Does it not work for you when using the `UseNpmCi` flag described above?

**Comment by leftfieldhero** [comment]
@torresxb1 Thanks for getting back to me. I found this issue and didn't know that the revert was reverted. I'll go ahead and give it a try, when I have an opportunity, and report back.

**Pull request merged**
