### PR TITLE
fix: `sam deploy` fails because bootstap stack is not created 

### PR DESCRIPTION
**Pull request by xanagi**
#### Which issue(s) does this change fix?

#3243

#### Why is this change necessary?

`sam deploy` fails if the bootstrap CFn stack is not created yet.

The reason is that the creation of `SamCliSourceBucketBucketPolicy` fails.
The Events tab of CFn console tells "The specified bucket is not valid. (Service: Amazon S3; Status Code: 400; Error Code: InvalidBucketName)".

#### How does it address the issue?

`!Ref` can only be used in YAML.
All `"!Ref foo"` are changed to `{"Ref": "foo"}`.

#### Checklist

- [ ] Add input/output [type hints](https://docs.python.org/3/library/typing.html) to new functions/methods
- [ ] Write design document ([Do I need to write a design document?](https://github.com/aws/aws-sam-cli/blob/develop/DEVELOPMENT_GUIDE.md#design-document))
- [ ] Write unit tests
- [ ] Write/update functional tests
- [ ] Write/update integration tests
- [x] `make pr` passes
- [ ] `make update-reproducible-reqs` if dependencies were changed
- [ ] Write documentation

By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0).

### CODE REVIEW

**Comment by punkstar** [comment]
Looks like this change worked for me when changed locally. Thanks!

**Comment by igorlg** [comment]
Need to re-run the failed job, the [error message](https://ci.appveyor.com/project/AWSSAMCLI/aws-sam-cli/builds/40638722/job/dm7weng3fhfwcbh1/messages) was a job timeout due to "maximum allowed time for your plan" (180 minutes).

**Comment by xanagi** [comment]
@igorlg Thanks! I re-ran jobs and now they are all successful.

**Comment by eh-admin** [comment]
stupid question: but how do i incorporate this fix if i have sam 1.30.0 installed? Do I need to wait for a new version to be released (e.g. 1.30.1)? Or is there a simple way to incorporate these changes prior to that?

**Comment by xanagi** [comment]
@eh-admin 
A dirty and quick way is overwriting the installed bootstrap.py with [this](https://github.com/aws/aws-sam-cli/blob/69db4354513b316a08e5929fbe92be41b6b4fc44/samcli/lib/bootstrap/bootstrap.py).
The file to overwrite can be found at `/usr/local/Cellar/aws-sam-cli/1.30.0/libexec/lib/python3.8/site-packages/samcli/lib/bootstrap/bootstrap.py` if you installed sam 1.30.0 with brew on mac.

**Comment by eh-admin** [comment]
> @eh-admin
> A dirty and quick way is overwriting the installed bootstrap.py with [this](https://github.com/aws/aws-sam-cli/blob/69db4354513b316a08e5929fbe92be41b6b4fc44/samcli/lib/bootstrap/bootstrap.py).
> The file to overwrite can be found at `/usr/local/Cellar/aws-sam-cli/1.30.0/libexec/lib/python3.8/site-packages/samcli/lib/bootstrap/bootstrap.py` if you installed sam 1.30.0 with brew on mac.

thanks! will try that out

**Comment by eh-admin** [comment]
> @eh-admin
> A dirty and quick way is overwriting the installed bootstrap.py with [this](https://github.com/aws/aws-sam-cli/blob/69db4354513b316a08e5929fbe92be41b6b4fc44/samcli/lib/bootstrap/bootstrap.py).
> The file to overwrite can be found at `/usr/local/Cellar/aws-sam-cli/1.30.0/libexec/lib/python3.8/site-packages/samcli/lib/bootstrap/bootstrap.py` if you installed sam 1.30.0 with brew on mac.

i couldn't manage to locate the bootstrap.py file in my installation (installed via the instructions at https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-install-linux.html - step#4)

```
ll /usr/local/aws-sam-cli/1.30.0/dist/ <only dirs>
_struct/
aws_lambda_builders/
boto3/
botocore/
certifi/
importlib_metadata-4.0.1-py3.7.egg-info/
include/
jsonschema/
jsonschema-3.2.0-py3.7.egg-info/
lib/
markupsafe/
pytz/
regex/
samcli/
samtranslator/
text_unidecode/
yaml/
zlib/
```

**Comment by xanagi** [comment]
Linux version of sam is distributed as a PyInstaller binary. I don't know an easy way to patch it. Sorry...

**Review by sriram-mv — APPROVED** [review]

**Comment by sriram-mv** [comment]
Thanks for providing the fix! We are in the process of verifying if this works as expected.

**Review by CoshUS — APPROVED** [review]

**Pull request merged**
