### PR TITLE
feat: adding `dotnet` build method that is version agnostic

### PR DESCRIPTION
**Pull request by Beau-Gosse-dev**
Tested with `SAM_CLI_DEV=1 pytest tests/integration -k "test_dotnet_al2_2_provided_al2"`
`1 passed, 2102 deselected in 17.34s`

#### Which issue(s) does this change fix?
#7463

#### Why is this change necessary?
See issue

#### How does it address the issue?
Adds dotnet build method

#### What side effects does this change have?
dotnet7 build method is now unnecessary, but kept for backwards compatibility. 

#### Mandatory Checklist
**PRs will only be reviewed after checklist is complete**

- [ ] Add input/output [type hints](https://docs.python.org/3/library/typing.html) to new functions/methods
- [ ] Write design document if needed ([Do I need to write a design document?](https://github.com/aws/aws-sam-cli/blob/develop/DEVELOPMENT_GUIDE.md#design-document))
- [ ] Write/update unit tests
- [X] Write/update integration tests
- [ ] Write/update functional tests if needed
- [ ] `make pr` passes
- [ ] `make update-reproducible-reqs` if dependencies were changed
- [ ] Write documentation

By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0).

### CODE REVIEW

**Comment by lucashuy** [comment]
Thanks for adding the flag for a generic `dotnet` method. Looks like you might just need to run the linter with `make format`, and a sanity check with `make pr` to pass the Github Actions.

**Comment by Beau-Gosse-dev** [comment]
Thanks. `make format` is working now and `make pr` has only 1 unrelated test failing:

```
FAILED tests/unit/commands/local/cli_common/test_invoke_context.py::TestInvokeContext_add_account_id_to_global::test_must_work_with_no_token - AssertionError: {'AWS::AccountId': '9**********1'} is not None
=========== 1 failed
```

**Comment by Beau-Gosse-dev** [comment]
Looks like the test failure is unrelated: `FAILED tests/integration/init/test_init_command.py::TestBasicInitCommand::test_init_command_go_provided_image - AssertionError: 1 != 0`

**Review by hawflau — APPROVED** [review]
LGTM. Thanks for the contribution!

**Review by sidhujus — APPROVED** [review]

**Pull request merged**
