### PR TITLE
Fix pipeline template generation from custom git repositories

### PR DESCRIPTION
**Pull request by kfr2**
#### Which issue(s) does this change fix?
#4206

#### Why is this change necessary?
Without this change, custom git repositories cannot be used for pipeline template generation.

#### How does it address the issue?
This commit restructures the `_generate_from_custom_location()` function to ensure `self._generate_from_pipeline_template()` is called within the context manager under which the custom git repository is cloned. 

#### What side effects does this change have?
None.

#### Mandatory Checklist
**PRs will only be reviewed after checklist is complete**

- [x] Add input/output [type hints](https://docs.python.org/3/library/typing.html) to new functions/methods
- [x] Write design document if needed ([Do I need to write a design document?](https://github.com/aws/aws-sam-cli/blob/develop/DEVELOPMENT_GUIDE.md#design-document))
- [x] Write/update unit tests
- [x] Write/update integration tests
- [x] Write/update functional tests if needed
- [x] `make pr` passes
- [x] `make update-reproducible-reqs` if dependencies were changed
- [x] Write documentation

By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0).

### CODE REVIEW

**Comment by mndeveci** [comment]
Thanks for raising this PR! Can we add some tests to cover the case which is been fixed by this PR? So that we won't have the same issue by mistake later.

**Review by aahung — CHANGES_REQUESTED** [review]
thx for fixing it, lgtm, can we add a test for it as suggested by @mndeveci?

**Comment by kfr2** [comment]
@mndeveci @aahung Thanks for the feedback! I've added a test case which exercises the interactive workflow operating against a "remote" Git repository.

**Review by aahung — APPROVED** [review]

**Review by mndeveci — APPROVED** [review]

**Comment by kfr2** [comment]
@aahung @mndeveci Do y'all need me to do anything else for this pull request? The failing test doesn't seem to be related to anything I've changed.

**Comment by lucashuy** [comment]
I'll update this branch from develop, that way the tests are restarted 😃

**Review by lucashuy — APPROVED** [review]
Thanks for your contributions!

**Pull request merged**
