### PR TITLE
fix: Support is SAM template check if transform is in list format

### PR DESCRIPTION
**Pull request by GavinZZ**
#### Which issue(s) does this change fix?

https://github.com/aws/aws-sam-cli/pull/2907/files#diff-f8525e6d2c30c548dc7271ad348b78778a72ebc24ff139de94c7a6d75dd60cf0

https://github.com/aws/serverless-application-model/issues/2960#issuecomment-1449180941

#### Why is this change necessary?
https://github.com/aws/serverless-application-model/issues/1108
We added a warning whenever customers defines a SAM API named "ServerlessRestApi". However, the warning is missing if customers use an array formatted Transform.
`Transform:  - AWS::Serverless-2016-10-31`

#### How does it address the issue?
Support array formatted Transform.

#### Mandatory Checklist
**PRs will only be reviewed after checklist is complete**

- [x] Add input/output [type hints](https://docs.python.org/3/library/typing.html) to new functions/methods
- [x] Write design document if needed ([Do I need to write a design document?](https://github.com/aws/aws-sam-cli/blob/develop/DEVELOPMENT_GUIDE.md#design-document))
- [x] Write/update unit tests
- [x] Write/update integration tests
- [x] Write/update functional tests if needed
- [x] `make pr` passes
- [x] `make update-reproducible-reqs` if dependencies were changed
- [x] Write documentation

By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0).

### CODE REVIEW

**Comment by GavinZZ** [comment]
See relevant issue: https://github.com/aws/serverless-application-model/issues/2960#issuecomment-1449180941

**Review by mndeveci — APPROVED** [review]
Thank you for addressing this. If you can also add this case to the `check_implicit_api_resource_ids` tests, that would be great!

**Review by hoffa — APPROVED** [review]

**Review by qingchm — CHANGES_REQUESTED** [review]
Let's update test_run_build_context test to add proper assertions to call _is_sam_template() as well to improve coverage

**Comment by GavinZZ** [comment]
Screen Shot 2023-02-28 at 5 59 13 PM

Verified that it works.

**Review by qingchm — APPROVED** [review]

**Pull request merged**
