### PR TITLE
Don't use layer.name in LayerBuildDefinition.__str__

### PR DESCRIPTION
**Pull request by asgarciap**
#### Which issue(s) does this change fix?

#2666 

#### Why is this change necessary?
`LayerBuildDefinition.layer` is set to `None` in `LayerBuildDefinition.__init__`, hence it is not guaranteed that it is actually set when calling `LayerBuildDefinition.__str__.` Also, currently `LayerBuildDefinition.name` is always initialized with `layer.name` in [app_builder.py](https://github.com/aws/aws-sam-cli/blob/283e546097f7520da740560de8a963ea387098dd/samcli/lib/build/app_builder.py#L202), so using `layer.name` in the `__str__` method dont add any new valuable debug info.

#### How does it address the issue?
Prevent using a not set var in the `__str__` method.

#### What side effects does this change have?
None

#### Checklist

- [ ] Add input/output [type hints](https://docs.python.org/3/library/typing.html) to new functions/methods
- [ ] Write design document ([Do I need to write a design document?](https://github.com/aws/aws-sam-cli/blob/develop/DEVELOPMENT_GUIDE.md#design-document))
- [ ] Write unit tests
- [ ] Write/update functional tests
- [ ] Write/update integration tests
- [x] `make pr` passes
- [ ] `make update-reproducible-reqs` if dependencies were changed
- [ ] Write documentation

By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0).

### CODE REVIEW

**Review by aahung — APPROVED** [review]
LGTM

**Review by sriram-mv — COMMENTED** [review]
Thank you for your contribution! This looks great! could you update the test for this method if there is one as well!

**Comment by asgarciap** [comment]
Hi @sriram-mv I don't see any test for this method, and to be honest I think it doesn't worth to add a new one, since this is just a function used to get a string representation of the LayerBuildDefinition to be used in debug messages.
Nevertheless, I can see there is a lack of unit tests for LayerBuildDefinition in general, so I think I will add in a separate PR more tests there. 
https://github.com/aws/aws-sam-cli/blob/e1afb465ead5a91ca09b28f292c5098666ab89a0/tests/unit/lib/build_module/test_build_graph.py#L291

**Review by sriram-mv — APPROVED** [review]

**Comment by asgarciap** [comment]
Can anyone please point me out if I have to do anything else in order to get this PR merged? I see it already has the minimum required approvals but  I'm not authorized to merge it though. 😄

**Comment by aahung** [comment]
> Can anyone please point me out if I have to do anything else in order to get this PR merged? I see it already has the minimum required approvals but I'm not authorized to merge it though. 😄

@asgarciap I will merge this PR as soon as CI check completes. Thanks for reminding us!

**Pull request merged**
