### PR TITLE
enabled cors support via openapi extensions

### PR DESCRIPTION
**Pull request by brandonryan**
#### Why is this change necessary?
API Gateway supports cors via openapi extensions. This feature is needed for my project because I want to use ApiGatewayV2 resources

#### How does it address the issue?
Adds swagger support for x-amazon-apigateway-cors

#### What side effects does this change have?
None as far as I know

#### Checklist

- [X] Add input/output [type hints](https://docs.python.org/3/library/typing.html) to new functions/methods
- [ ] Write design document ([Do I need to write a design document?](https://github.com/aws/aws-sam-cli/blob/develop/DEVELOPMENT_GUIDE.md#design-document))
- [ ] Write unit tests
- [X] Write/update functional tests
- [X] Write/update integration tests
- [X] `make pr` passes
- [ ] `make update-reproducible-reqs` if dependencies were changed
- [X] Write documentation

By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0).

### CODE REVIEW

**Comment by brandonryan** [comment]
Any review update? Still blocking a project im working on.

**Comment by jfuss** [comment]
@brandonryan Sorry for the delay. Are you interesting in getting this through? I am trying to go through our PRs and close the ones no longer active. Happy to review it but if your not interested anymore (which I would understand), I would rather close.

**Comment by brandonryan** [comment]
Yes. I think it should be merged to help with apigateway feature parity. I currently moved to abandoning sam cli all together because it didn't have this feature.

**Comment by jfuss** [comment]
@brandonryan Sounds good. I am currently trying to organize myself on what I need to review. So will add this to my list. Hoping to have a review out to you by the end of the week.

**Review by jfuss — CHANGES_REQUESTED** [review]
Seems like a reasonable change. Can we add integration tests to cover different cases to make sure this behaves as we expect.

**Comment by jfuss** [comment]
Closing given no response. Feel free to re-open and address comments and we will have another look.

**Pull request closed without merging**
